"""Utilitarios de evolucao de schema do banco."""

from __future__ import annotations

from sqlalchemy import text

from src.banco.database import get_engine


def garantir_colunas_fato_dengue(schema: str = "saude", table_name: str = "fato_dengue_casos") -> None:
    """Garante colunas adicionais da fato usadas no BI."""
    raw_date_cols = [
        "dt_alrm",
        "dt_digita",
        "dt_grav",
        "dt_invest",
        "dt_notific",
        "dt_obito",
    ]
    raw_text_cols = [
        "tp_not",
        "id_agravo",
        "sem_not",
        "nu_ano",
        "sg_uf_not",
        "id_municip",
        "id_regiona",
        "ano_nasc",
        "sem_pri",
        "sg_uf",
        "id_mn_resi",
        "id_rg_resi",
        "id_pais",
        "id_ocupa_n",
        "tpautocto",
        "coufinf",
        "copaisinf",
        "comuninf",
        "classi_fin",
        "criterio",
        "doenca_tra",
        "clinc_chik",
        "evolucao",
        "alrm_hipot",
        "alrm_plaq",
        "alrm_vom",
        "alrm_sang",
        "alrm_hemat",
        "alrm_abdom",
        "alrm_letar",
        "alrm_hepat",
        "alrm_liq",
        "grav_pulso",
        "grav_conv",
        "grav_ench",
        "grav_insuf",
        "grav_taqui",
        "grav_extre",
        "grav_hipot",
        "grav_hemat",
        "grav_melen",
        "grav_metro",
        "grav_sang",
        "grav_ast",
        "grav_mioc",
        "grav_consc",
        "grav_orgao",
        "mani_hemor",
        "epistaxe",
        "gengivo",
        "metro",
        "petequias",
        "hematura",
        "sangram",
        "laco_n",
        "plasmatico",
        "evidencia",
        "plaq_menor",
        "con_fhd",
        "complica",
        "tp_sistema",
        "nduplic_n",
        "cs_flxret",
        "flxrecebi",
        "migrado_w",
        "resul_pcr",
    ]

    stmts = [
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_sin_pri DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_encerra DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS cs_sexo VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS nu_idade_n VARCHAR(8)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS cs_gestant VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS cs_raca VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS cs_escol_n VARCHAR(4)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS id_unidade VARCHAR(20)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS hospitaliz VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS febre VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS mialgia VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS cefaleia VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS exantema VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS vomito VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS nausea VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dor_costas VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS conjuntvit VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS artrite VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS artralgia VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS petequia_n VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS leucopenia VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS laco VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dor_retro VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS resul_soro VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_chik_s1 DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_chik_s2 DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_prnt DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS res_chiks1 VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS res_chiks2 VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS resul_prnt VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_soro DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS resul_ns1 VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_ns1 DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_viral DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS resul_vi_n VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_pcr DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS resul_pcr_ VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS sorotipo VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS histopa_n VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS imunoh_n VARCHAR(2)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS dt_interna DATE",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS diabetes VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS hematolog VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS hepatopat VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS renal VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS hipertensa VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS acido_pept VARCHAR(1)",
        f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS auto_imune VARCHAR(1)",
    ]
    stmts.extend(
        [f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS {col} DATE" for col in raw_date_cols]
    )
    stmts.extend(
        [f"ALTER TABLE {schema}.{table_name} ADD COLUMN IF NOT EXISTS {col} VARCHAR(40)" for col in raw_text_cols]
    )
    with get_engine().begin() as conn:
        for stmt in stmts:
            conn.execute(text(stmt))
