CREATE SCHEMA IF NOT EXISTS saude;

CREATE TABLE IF NOT EXISTS saude.fato_dengue_casos (
    id BIGSERIAL PRIMARY KEY,
    municipio VARCHAR(120) NOT NULL,
    uf CHAR(2),
    data_notificacao DATE,
    semana_epidemiologica INTEGER,
    classificacao_final VARCHAR(80),
    evolucao_caso VARCHAR(80),
    cs_sexo VARCHAR(1),
    nu_idade_n VARCHAR(8),
    cs_gestant VARCHAR(2),
    cs_raca VARCHAR(2),
    cs_escol_n VARCHAR(4),
    id_unidade VARCHAR(20),
    hospitaliz VARCHAR(2),
    febre VARCHAR(1),
    mialgia VARCHAR(1),
    cefaleia VARCHAR(1),
    exantema VARCHAR(1),
    vomito VARCHAR(1),
    nausea VARCHAR(1),
    dor_costas VARCHAR(1),
    conjuntvit VARCHAR(1),
    artrite VARCHAR(1),
    artralgia VARCHAR(1),
    petequia_n VARCHAR(1),
    leucopenia VARCHAR(1),
    laco VARCHAR(1),
    dor_retro VARCHAR(1),
    dt_chik_s1 DATE,
    dt_chik_s2 DATE,
    dt_prnt DATE,
    res_chiks1 VARCHAR(2),
    res_chiks2 VARCHAR(2),
    resul_prnt VARCHAR(2),
    dt_soro DATE,
    resul_soro VARCHAR(2),
    dt_ns1 DATE,
    resul_ns1 VARCHAR(2),
    dt_viral DATE,
    resul_vi_n VARCHAR(2),
    dt_pcr DATE,
    resul_pcr_ VARCHAR(2),
    sorotipo VARCHAR(2),
    histopa_n VARCHAR(2),
    imunoh_n VARCHAR(2),
    dt_interna DATE,
    diabetes VARCHAR(1),
    hematolog VARCHAR(1),
    hepatopat VARCHAR(1),
    renal VARCHAR(1),
    hipertensa VARCHAR(1),
    acido_pept VARCHAR(1),
    auto_imune VARCHAR(1),
    data_carga TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fato_dengue_data_notificacao
    ON saude.fato_dengue_casos (data_notificacao);

CREATE INDEX IF NOT EXISTS idx_fato_dengue_municipio
    ON saude.fato_dengue_casos (municipio);
